### ISSUE TITLE
SuSEconnect url addition (feature request)

### ISSUE THREAD

**Issue by GITStone-tech** [stdevel/ansible-uyuni#42]
Hi Christian

It would be nice to have a parameter uyuni_scc_url in order to specify URL to use for registration; could be useful e.g. in cloud environments to specify --url=scc.suse.com 

Thanks, Dietmar

**Comment by stdevel** [comment]
Hi Dietmar,
thanks for the feature request!

I didn't know, that there are additional SCC URLs - only knew `scc.suse.com` so far. Will have a look at it. :)

Best wishes,
Christian.

**Comment by GITStone-tech** [comment]
Hi Chistian

Hm ... I am not 100% sure, but could be helpful while working e.g. in Azure gettig base subscription by Azure Marketplace "image" and registering SuSE Manager in SCC afterwards.

I have just done the change by myself, but as I am not that familiar with writing ansible modules I decided to request it.

Regards, Dietmar

**Comment by stdevel** [comment]
I implemented the variable `uyuni_scc_url` in the `feat-ssc_url-42` branch. Can you give it a try?

**Comment by GITStone-tech** [comment]
Hi Christian

As far as I can see it is working :-)

Also thanks for respecting python3 channel - had fixed this before manually.

Regards, Dietmar

**Comment by GITStone-tech** [comment]
Hi Christian

I think I have done a misconception which will affect installations done in e.g. Azure Cloud by using marketplace - if 

SUSEConnect --status --url {{ uyuni_scc_url }} 

is run from _prepare_sles.yml_ e.g. it will lead to an error, because registration is done by using _smt-azure.susecloud.net_ and not _{{ uyuni_scc_url }}_

So I would like to ask _not_ to merge right now.

I will check if we can have a workaround ...

Thanks, Dietmar

**Comment by GITStone-tech** [comment]
Ok - I think I got it.

I have changed _prepare_sles.yml_ in tasks according:

_myhost:ansible stone$ cat roles/suma_install/tasks/prepare_sles.yml 
---
- name: Check system registration
  ansible.builtin.command: SUSEConnect --status
[...]

- name: Prepare JeOS
[...]

- name: Cleanup registration
  ansible.builtin.command: "SUSEConnect --cleanup"
  when:
    - uyuni_scc_check_registration
  become: true
  
- name: Register system
[...]
myhost:ansible stone$_

_SUSEConnect --status_ has to be run without specifying the URL so it takes URL from _/etc/SUSEConnect_ if the system has registered previously.

After that we need to clean up registration in order to make registration possible in the next step (this is necessary e.g. having an marketplace installation in e.g. Azure).

Regards, Dietmar

**Comment by GITStone-tech** [comment]
p.s: of course a de-registration followed by cleanup would be best

**Comment by stdevel** [comment]
Hi Dietmar,
sorry for getting up on this so late, but I've been busy.

I've removed the `--url` parameter from the `SUSEConnect --status` task.

What do you think about adding an edge case for cleanining up registration and re-registering if the desired SCC url is not set in `/etc/SUSEConnect`? Otherwise the role would become non-idempotent as it would clean-up and register upon every run.

Best wishes,
Christian.

**Comment by GITStone-tech** [comment]
Hi Christian

Thanks for your reply.

I think the --url parameter is no longer needed as SuSE recommends to de-register cloud guest before registering them at SuSE Manager; this applies to SuSE Manager installation, too.

Have a look at https://documentation.suse.com/suma/4.2/en/suse-manager/client-configuration/clients-pubcloud.html#_prepare_on_demand_images <https://documentation.suse.com/suma/4.2/en/suse-manager/client-configuration/clients-pubcloud.html#_prepare_on_demand_images> for the de-register process of public cloud clients.

I am sorry but I cannot find the support article URL for SuSE Manager itself, but if we start with SLES15SP3 for SuMa 4.2 (or SP4 for 4.3) in e.g. Azure it is the same procedure as with client registration on SuSE Manager ...

SuSE themselves recommend to use a SuSE Manager public cloud image as provided by Azure marketplace so support information on alternative installations are hard to find.

I will get in touch with you as I have done a major rewriting of the role and additional modules at the current customer ...

Regards, Dietmar

**Comment by stdevel** [comment]
Hi Dietmar,
thanks for the feedback!

As I'm going to move this role to [a collection](https://github.com/stdevel/ansible-collection-uyuni) very soon, I'm closing this issue. Feel free to open an issue for the collection again, if you're ready.

Best wishes,
Christian.
