### ISSUE TITLE
Modules acitivation - python2 for SLES SP4 not possible

### ISSUE THREAD

**Issue by herrmie** [stdevel/ansible-uyuni#45]
Hello Christian,

when installing Suse Manager on SP4, it is not possible to activate the module python2
```
- name: sle-module-python2
   identifier: "sle-module-python2/{{ ansible_distribution_version }}/{{ ansible_architecture }}"
```
I have changed it to python3 and it was working. 
So, maybe you need to check which SP is installed to put the right python module.

Best regards,
steffen

**Comment by stdevel** [comment]
Investigating in branch `bug-python3_module-45`.
